apiVersion: v1
kind: Service
metadata:
  name: migration-myaktion-frontend-service
spec:
  selector:
    app: migration-myaktion-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30002
  type: NodePort

