kind: PersistentVolume
apiVersion: v1
metadata:
  name: migration-myaktion-db-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/migration"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: migration-myaktion-db
  name: migration-myaktion-db-pv-claim
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100M
